version: '3.5'

services:
  app:
    build: .
    ports:
      - 4000:4000
    volumes:
      - '.:/usr/src/app'
      - docker-composer-elixir-mix:/root/.mix

volumes:
  docker-composer-elixir-mix:

networks:
  local:

